Annotation relation
fazlmakhsudov/orm pull request #5
Opened 2020-05-05 13:35 UTC by Dimon-Mvp

2020-05-05 17:01 UTC, KonstantinOvcharenko approved these changes

2020-05-05 17:04 UTC, fazlmakhsudov approved these changes

2020-05-06 12:06 UTC, teaFunny requested changes

2020-05-06 12:06 UTC, teaFunny commented on src/main/java/com/practice/orm/annotation/relationalAnotation/relationHandler/RelationHandler.java
> +    private static TableDB getForeignKeyForManyToMany(Field field, Class<?> clazz) throws Exception {
Please refactor it

2020-05-06 15:31 UTC, Dimon-Mvp commented on src/main/java/com/practice/orm/annotation/relationalAnotation/relationHandler/RelationHandler.java
> +    private static TableDB getForeignKeyForManyToMany(Field field, Class<?> clazz) throws Exception {
Can you check?

2020-05-07 09:58 UTC, teaFunny approved these changes

2020-05-07 09:58 UTC, merged